import type { Metadata } from "next";
import LayoutProvider from "@/components/LayoutProvider";
import "./globals.css";
import "./../stylesheets/commonClasses.css";
import "./../stylesheets/antdOverride.css";
import "./../stylesheets/layout.css";

export const metadata: Metadata = {
  title: "Researchly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <LayoutProvider>{children}</LayoutProvider>;
}
